name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint and fix with Ruff
      run: |
        ruff check . --fix
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install Node packages and Build
      run: |
        if [ -f "package.json" ]; then
          npm install
          npm run build --if-present
        fi
        
    - name: Test with pytest
      run: |
        if [ -d "tests" ] || [ -f "pytest.ini" ]; then pytest; fi
        
    - name: Commit Fixed Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto-Guard: Sanitized code, syntax, and packages."
        push_options: '--force'
